### ISSUE TITLE
When will the .cpp file be released

### ISSUE THREAD

**Issue by fanzy1234** [torresszy/auto_calibration#2]
haha
my email 1138589626@qq.com

**Comment by yunhaoqiao** [comment]
my email 2750038492@qq.com

**Comment by liangwenkai** [comment]
can you release the source code?  my email is wkliang@stu.xidian.edu.cn
thank you !

**Comment by angiend** [comment]
would you have any plan to release the source code?
angiend1517@126.com

**Comment by torresszy** [comment]
Sorry guys, the source code will not be released due to privacy reasons. This repository is meant for personal recruitment uses only and is not an open-source project. I suggest consulting existing research papers if this project is something you want to achieve.
